// Code generated by protoc-gen-go.
// source: common.ext.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	common.ext.proto
	sceneManager.ext.proto

It has these top-level messages:
	Point
	MoveRequest
	MoveResponse
	InGameRequest
	InGameResponse
	MapListRequest
	MapListResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	X int64 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z int64 `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Point) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "pb.Point")
}

func init() { proto.RegisterFile("common.ext.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x4b, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0x32, 0xe4, 0x62, 0x0d, 0xc8, 0xcf, 0xcc, 0x2b, 0x11, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0x25, 0x98, 0x20, 0xbc, 0x4a, 0x10,
	0xaf, 0x4a, 0x82, 0x19, 0xc2, 0xab, 0x4a, 0x62, 0x03, 0xeb, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xbb, 0x36, 0x7f, 0xf6, 0x51, 0x00, 0x00, 0x00,
}
