// Code generated by protoc-gen-go.
// source: sceneManager.ext.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sceneManager.ext.proto

It has these top-level messages:
	JoinRequest
	JoinResponse
	InGameRequest
	InGameResponse
	MapListRequest
	MapListResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JoinRequest struct {
	MapId int64 `protobuf:"varint,1,opt,name=mapId" json:"mapId,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *JoinRequest) GetMapId() int64 {
	if m != nil {
		return m.MapId
	}
	return 0
}

type JoinResponse struct {
	MapId int64 `protobuf:"varint,1,opt,name=mapId" json:"mapId,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JoinResponse) GetMapId() int64 {
	if m != nil {
		return m.MapId
	}
	return 0
}

type InGameRequest struct {
}

func (m *InGameRequest) Reset()                    { *m = InGameRequest{} }
func (m *InGameRequest) String() string            { return proto.CompactTextString(m) }
func (*InGameRequest) ProtoMessage()               {}
func (*InGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InGameResponse struct {
}

func (m *InGameResponse) Reset()                    { *m = InGameResponse{} }
func (m *InGameResponse) String() string            { return proto.CompactTextString(m) }
func (*InGameResponse) ProtoMessage()               {}
func (*InGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type MapListRequest struct {
}

func (m *MapListRequest) Reset()                    { *m = MapListRequest{} }
func (m *MapListRequest) String() string            { return proto.CompactTextString(m) }
func (*MapListRequest) ProtoMessage()               {}
func (*MapListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type MapListResponse struct {
}

func (m *MapListResponse) Reset()                    { *m = MapListResponse{} }
func (m *MapListResponse) String() string            { return proto.CompactTextString(m) }
func (*MapListResponse) ProtoMessage()               {}
func (*MapListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*JoinRequest)(nil), "pb.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "pb.JoinResponse")
	proto.RegisterType((*InGameRequest)(nil), "pb.InGameRequest")
	proto.RegisterType((*InGameResponse)(nil), "pb.InGameResponse")
	proto.RegisterType((*MapListRequest)(nil), "pb.MapListRequest")
	proto.RegisterType((*MapListResponse)(nil), "pb.MapListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RoomManagerExtService service

type RoomManagerExtServiceClient interface {
	// 加入某张地图
	Join(ctx context.Context, in *JoinRequest, opts ...client.CallOption) (*JoinResponse, error)
	InGame(ctx context.Context, in *InGameRequest, opts ...client.CallOption) (*InGameResponse, error)
	// 房间列表
	MapList(ctx context.Context, in *MapListRequest, opts ...client.CallOption) (*MapListResponse, error)
}

type roomManagerExtServiceClient struct {
	c           client.Client
	serviceName string
}

func NewRoomManagerExtServiceClient(serviceName string, c client.Client) RoomManagerExtServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &roomManagerExtServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *roomManagerExtServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...client.CallOption) (*JoinResponse, error) {
	req := c.c.NewRequest(c.serviceName, "RoomManagerExtService.Join", in)
	out := new(JoinResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerExtServiceClient) InGame(ctx context.Context, in *InGameRequest, opts ...client.CallOption) (*InGameResponse, error) {
	req := c.c.NewRequest(c.serviceName, "RoomManagerExtService.InGame", in)
	out := new(InGameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerExtServiceClient) MapList(ctx context.Context, in *MapListRequest, opts ...client.CallOption) (*MapListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "RoomManagerExtService.MapList", in)
	out := new(MapListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomManagerExtService service

type RoomManagerExtServiceHandler interface {
	// 加入某张地图
	Join(context.Context, *JoinRequest, *JoinResponse) error
	InGame(context.Context, *InGameRequest, *InGameResponse) error
	// 房间列表
	MapList(context.Context, *MapListRequest, *MapListResponse) error
}

func RegisterRoomManagerExtServiceHandler(s server.Server, hdlr RoomManagerExtServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&RoomManagerExtService{hdlr}, opts...))
}

type RoomManagerExtService struct {
	RoomManagerExtServiceHandler
}

func (h *RoomManagerExtService) Join(ctx context.Context, in *JoinRequest, out *JoinResponse) error {
	return h.RoomManagerExtServiceHandler.Join(ctx, in, out)
}

func (h *RoomManagerExtService) InGame(ctx context.Context, in *InGameRequest, out *InGameResponse) error {
	return h.RoomManagerExtServiceHandler.InGame(ctx, in, out)
}

func (h *RoomManagerExtService) MapList(ctx context.Context, in *MapListRequest, out *MapListResponse) error {
	return h.RoomManagerExtServiceHandler.MapList(ctx, in, out)
}

func init() { proto.RegisterFile("sceneManager.ext.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x4e, 0xcd,
	0x4b, 0xf5, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0xd2, 0x4b, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe6, 0xe2, 0xf6, 0xca, 0xcf, 0xcc, 0x0b, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0x4d, 0x2c, 0xf0, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x94, 0x54, 0xb8, 0x78, 0x20, 0x8a, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x71, 0xa8, 0xe2, 0xe7, 0xe2, 0xf5, 0xcc, 0x73, 0x4f, 0xcc, 0x4d, 0x85, 0x1a,
	0xa6, 0x24, 0xc0, 0xc5, 0x07, 0x13, 0x80, 0x68, 0x04, 0x89, 0xf8, 0x26, 0x16, 0xf8, 0x64, 0x16,
	0x97, 0xc0, 0xd4, 0x08, 0x72, 0xf1, 0xc3, 0x45, 0x20, 0x8a, 0x8c, 0xd6, 0x32, 0x72, 0x89, 0x06,
	0xe5, 0xe7, 0xe7, 0x42, 0x1d, 0xec, 0x5a, 0x51, 0x12, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a,
	0xa4, 0xcd, 0xc5, 0x02, 0x72, 0x87, 0x10, 0xbf, 0x5e, 0x41, 0x92, 0x1e, 0x92, 0xb3, 0xa5, 0x04,
	0x10, 0x02, 0x50, 0x9b, 0x18, 0x84, 0x0c, 0xb9, 0xd8, 0x20, 0xb6, 0x0b, 0x09, 0x82, 0x64, 0x51,
	0x9c, 0x26, 0x25, 0x84, 0x2c, 0x04, 0xd7, 0x62, 0xc2, 0xc5, 0x0e, 0x75, 0x8c, 0x10, 0x58, 0x01,
	0xaa, 0x5b, 0xa5, 0x84, 0x51, 0xc4, 0x60, 0xba, 0x92, 0xd8, 0xc0, 0xa1, 0x69, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0x87, 0x64, 0x98, 0x67, 0x01, 0x00, 0x00,
}
